#pragma once

#include <string>

#include "minecraftpe/util/AABB.h"
#include "minecraftpe/level/Brightness.h"

class Random;
class BlockSource;
class BlockPos;
class Vec3;
class Entity;
class Mob;
class Player;

class Block
{
public:
	class SoundType
	{
	public:

	};

	static Block *mAcaciaFenceGate;
	static Block *mAcaciaStairs;
	static Block *mActivatorRail;
	static Block *mAir;
	static Block *mAnvil;
	static Block *mBed;
	static Block *mBedrock;
	static Block *mBeetrootCrop;
	static Block *mBirchFenceGate;
	static Block *mBirchStairs;
	static Block *mBookshelf;
	static Block *mBrewingStand;
	static Block *mBrick;
	static Block *mBrickStairs;
	static Block *mBrownMushroom;
	static Block *mBrownMushroomBlock;
	static Block *mCactus;
	static Block *mCake;
	static Block *mCarrotCrop;
	static Block *mChest;
	static Block *mClay;
	static Block *mCoalBlock;
	static Block *mCoalOre;
	static Block *mCobblestone;
	static Block *mCobblestoneWall;
	static Block *mCocoa;
	static Block *mDarkOakFenceGate;
	static Block *mDarkOakStairs;
	static Block *mDaylightDetector;
	static Block *mDaylightDetectorInverted;
	static Block *mDeadBush;
	static Block *mDetectorRail;
	static Block *mDiamondBlock;
	static Block *mDiamondOre;
	static Block *mDirt;
	static Block *mDoublePlant;
	static Block *mDoubleStoneSlab;
	static Block *mDoubleWoodenSlab;
	static Block *mEmeraldBlock;
	static Block *mEmeraldOre;
	static Block *mEnchantingTable;
	static Block *mEndPortalFrame;
	static Block *mEndStone;
	static Block *mFarmland;
	static Block *mFence;
	static Block *mFenceGateOak;
	static Block *mFire;
	static Block *mFlowerPot;
	static Block *mFlowingLava;
	static Block *mFlowingWater;
	static Block *mFurnace;
	static Block *mGlass;
	static Block *mGlassPane;
	static Block *mGlowStone;
	static Block *mGlowingObsidian;
	static Block *mGoldBlock;
	static Block *mGoldOre;
	static Block *mGoldenRail;
	static Block *mGrass;
	static Block *mGrassPathBlock;
	static Block *mGravel;
	static Block *mHardenedClay;
	static Block *mHayBlock;
	static Block *mHeavyWeightedPressurePlate;
	static Block *mIce;
	static Block *mInfoReserved6;
	static Block *mInfoUpdateGame1;
	static Block *mInfoUpdateGame2;
	static Block *mInvisibleBedrock;
	static Block *mIronBlock;
	static Block *mIronDoor;
	static Block *mIronFence;
	static Block *mIronOre;
	static Block *mIronTrapdoor;
	static Block *mJungleFenceGate;
	static Block *mJungleStairs;
	static Block *mLadder;
	static Block *mLapisBlock;
	static Block *mLapisOre;
	static Block *mLeaves;
	static Block *mLeaves2;
	static Block *mLever;
	static Block *mLightWeightedPressurePlate;
	static Block *mLitFurnace;
	static Block *mLitPumpkin;
	static Block *mLitRedStoneLamp;
	static Block *mLitRedStoneOre;
	static Block *mLitRedStoneTorch;
	static Block *mLog;
	static Block *mLog2;
	static Block *mMelon;
	static Block *mMelonStem;
	static Block *mMobSpawner;
	static Block *mMonsterStoneEgg;
	static Block *mMossyCobblestone;
	static Block *mMycelium;
	static Block *mNetherBrick;
	static Block *mNetherBrickStairs;
	static Block *mNetherFence;
	static Block *mNetherReactor;
	static Block *mNetherWart;
	static Block *mNetherrack;
	static Block *mNote;
	static Block *mOakStairs;
	static Block *mObsidian;
	static Block *mPackedIce;
	static Block *mPodzol;
	static Block *mPortal;
	static Block *mPotatoCrop;
	static Block *mPumpkin;
	static Block *mPumpkinStem;
	static Block *mQuartzBlock;
	static Block *mQuartzOre;
	static Block *mQuartzStairs;
	static Block *mRail;
	static Block *mRedFlower;
	static Block *mRedMushroom;
	static Block *mRedMushroomBlock;
	static Block *mRedStoneDust;
	static Block *mRedStoneOre;
	static Block *mRedstoneBlock;
	static Block *mReeds;
	static Block *mSand;
	static Block *mSandStone;
	static Block *mSandstoneStairs;
	static Block *mSapling;
	static Block *mSign;
	static Block *mSkull;
	static Block *mSnow;
	static Block *mSoulSand;
	static Block *mSponge;
	static Block *mSpruceStairs;
	static Block *mSpuceFenceGate;
	static Block *mStainedClay;
	static Block *mStillLava;
	static Block *mStillWater;
	static Block *mStone;
	static Block *mStoneBrick;
	static Block *mStoneBrickStairs;
	static Block *mStoneButton;
	static Block *mStonePressurePlate;
	static Block *mStoneSlab;
	static Block *mStoneStairs;
	static Block *mStonecutterBench;
	static Block *mTNT;
	static Block *mTallgrass;
	static Block *mTopSnow;
	static Block *mTorch;
	static Block *mTrapdoor;
	static Block *mTrappedChest;
	static Block *mTripwire;
	static Block *mTripwireHook;
	static Block *mUnlitRedStoneLamp;
	static Block *mUnlitRedStoneTorch;
	static Block *mVine;
	static Block *mWallSign;
	static Block *mWaterlily;
	static Block *mWeb;
	static Block *mWheatCrop;
	static Block *mWoodButton;
	static Block *mWoodPlanks;
	static Block *mWoodPressurePlate;
	static Block *mWoodenDoor;
	static Block *mWoodenDoorAcacia;
	static Block *mWoodenDoorBirch;
	static Block *mWoodenDoorDarkOak;
	static Block *mWoodenDoorJungle;
	static Block *mWoodenDoorSpruce;
	static Block *mWoodenSlab;
	static Block *mWool;
	static Block *mWoolCarpet;
	static Block *mWorkBench;
	static Block *mYellowFlower;

	char filler[4];		// 0
	unsigned char id;	// 4

	virtual ~Block();
	virtual void tick(BlockSource &, const BlockPos &, Random &);
	virtual void animateTick(BlockSource &, const BlockPos &, Random &);
	virtual void getVisualShape(BlockSource &, const BlockPos &, AABB &, bool);
	virtual void getVisualShape(unsigned char, AABB &, bool);
	virtual void getCollisionShape(AABB &, BlockSource &, const BlockPos &, Entity *);
	virtual void isObstructingChests(BlockSource &, const BlockPos &);
	virtual void shouldRenderFace(BlockSource &, const BlockPos &, signed char, const AABB &) const;
	virtual void getTexture(signed char);
	virtual void getTexture(signed char, int);
	virtual void getTexture(BlockSource &, const BlockPos &, signed char);
	virtual void getTessellatedUVs();
	virtual void getCarriedTexture(signed char, int);
	virtual void addAABBs(BlockSource &, const BlockPos &, const AABB *, std::vector<AABB> &);
	virtual void getAABB(BlockSource &, const BlockPos &, AABB &, int, bool, int);
	virtual void addCollisionShapes(BlockSource &, const BlockPos &, const AABB *, std::vector<AABB> &, Entity *);
	virtual void isCropBlock() const;
	virtual void isContainerBlock() const;
	virtual void isCraftingBlock() const;
	virtual void isInteractiveBlock() const;
	virtual void isWaterBlocking() const;
	virtual void isDoorBlock() const;
	virtual void isRedstoneBlock() const;
	virtual void isRedstoneAttachable() const;
	virtual void waterSpreadCausesSpawn() const;
	virtual void getRenderLayer(BlockSource &, const BlockPos &) const;
	virtual void getThickness() const;
	virtual void checkIsPathable(Entity &, const BlockPos &, const BlockPos &);
	virtual void onPlace(BlockSource &, const BlockPos &);
	virtual void onRemove(BlockSource &, const BlockPos &);
	virtual void onExploded(BlockSource &, const BlockPos &, Entity *);
	virtual void onStepOn(Entity &, const BlockPos &);
	virtual void onFallOn(BlockSource &, const BlockPos &, Entity *, float);
	virtual void onRedstoneUpdate(BlockSource &, const BlockPos &, int, bool);
	virtual void onLoaded(BlockSource &, const BlockPos &);
	virtual void onFertilized(BlockSource &, const BlockPos &, Player *);
	virtual void mayConsumeFertilizer(BlockSource &);
	virtual void mayPick();
	virtual void mayPick(BlockSource &, int, bool);
	virtual void mayPlace(BlockSource &, const BlockPos &, signed char);
	virtual void mayPlace(BlockSource &, const BlockPos &);
	virtual void tryToPlace(BlockSource &, const BlockPos &, unsigned char);
	virtual void destroy(BlockSource &, const BlockPos &, int, Entity *);
	virtual void playerWillDestroy(Player &, const BlockPos &, int);
	virtual void neighborChanged(BlockSource &, const BlockPos &, const BlockPos &);
	virtual void getSecondPart(BlockSource &, const BlockPos &, BlockPos &);
	virtual void onGraphicsModeChanged(bool, bool);
	virtual void getResource(Random &, int, int);
	virtual void getResourceCount(Random &, int, int);
	virtual void asItemInstance(BlockSource &, const BlockPos &, int) const;
	virtual void getDestroyProgress(Player &);
	virtual void spawnResources(BlockSource &, const BlockPos &, int, float, int);
	virtual void spawnBurnResources(BlockSource &, float, float, float);
	virtual void getExplosionResistance(Entity *);
	virtual void clip(BlockSource &, const BlockPos &, const Vec3 &, const Vec3 &, bool, int);
	virtual bool use(Player &, const BlockPos &);
	virtual void getPlacementDataValue(Mob &, const BlockPos &, signed char, const Vec3 &, int);
	virtual void prepareRender(BlockSource &, const BlockPos &);
	virtual void attack(Player *, const BlockPos &);
	virtual void handleEntityInside(BlockSource &, const BlockPos &, Entity *, Vec3 &);
	virtual void getColor(int);
	virtual void getColor(BlockSource &, const BlockPos &);
	virtual void isSeasonTinted(BlockSource &, const BlockPos &) const;
	virtual void entityInside(BlockSource &, const BlockPos &, Entity &);
	virtual void playerDestroy(Player *, const BlockPos &, int);
	virtual void canSurvive(BlockSource &, const BlockPos &);
	virtual void getExperienceDrop(Random &) const;
	virtual void canBeBuiltOver(BlockSource &, const BlockPos &) const;
	virtual void buildDescriptionName(const ItemInstance &) const;
	virtual void triggerEvent(BlockSource &, const BlockPos &, int, int);
	virtual void getTextureNum(int);
	virtual void getMobToSpawn(BlockSource &, const BlockPos &) const;
	virtual void getIconYOffset() const;
	virtual void shouldStopFalling(Entity &);
	virtual void calcGroundFriction(Mob &, const BlockPos &) const;
	virtual void canHaveExtraData() const;
	virtual void init();
	virtual void canBeSilkTouched() const;
	virtual void getSilkTouchItemInstance(unsigned char);
	virtual void setVisualShape(const Vec3 &, const Vec3 &);
	virtual void setSoundType(const SoundType &);
	virtual void setLightBlock(Brightness);
	virtual void setLightEmission(float);
	virtual void setExplodeable(float);
	virtual void setDestroyTime(float);
	virtual void setFriction(float);
	virtual void setTicking(bool);
	virtual void getSpawnResourcesAuxValue(unsigned char);
	bool isType(const Block *) const;
	static Block *lookupByName(const std::string &, bool);
};
