#pragma once

class ImageData;
class ImagePickingCallback;
class LoginInformation;
class UriListener;

class AppPlatform
{
public:
	AppPlatform();
	virtual ~AppPlatform();
	virtual void getImagePath(const std::string &, bool) = 0;
	virtual void loadPNG(ImageData &, const std::string &, bool) = 0;
	virtual void loadTGA(ImageData &, const std::string &);
	virtual void savePNG(const ImageData &, const std::string &);
	virtual void getKeyFromKeyCode(int, int, int);
	virtual void showKeyboard(const std::string &, int, bool);
	virtual void hideKeyboard();
	virtual void captureScreen(int, int, unsigned int, bool);
	virtual void swapBuffers() = 0;
	virtual void getSystemRegion() const = 0;
	virtual void getGraphicsVendor() = 0;
	virtual void getGraphicsRenderer() = 0;
	virtual void getGraphicsVersion() = 0;
	virtual void getGraphicsExtensions() = 0;
	virtual void pickImage(ImagePickingCallback &) = 0;
	virtual void setSleepEnabled(bool);
	virtual void getExternalStoragePath();
	virtual void getInternalStoragePath();
	virtual void playSound(const std::string &, float, float);
	virtual void showDialog(int);
	virtual void createUserInput();
	virtual void getUserInputStatus();
	virtual void getUserInput();
	virtual void _tick();
	virtual void getScreenWidth();
	virtual void getScreenHeight();
	virtual void getPixelsPerMillimeter();
	virtual void openLoginWindow();
	virtual void updateTextBoxText(const std::string &);
	virtual void isKeyboardVisible();
	virtual void getLoginInformation();
	virtual void setLoginInformation(const LoginInformation &);
	virtual void clearSessionIDAndRefreshToken();
	virtual void supportsVibration();
	virtual void vibrate(int);
	virtual void readAssetFile(const std::string &);
	virtual void listAssetFilesIn(const std::string &, const std::string &) const;
	virtual void getDateString(int);
	virtual void checkLicense();
	virtual void hasBuyButtonWhenInvalidLicense();
	virtual void uploadPlatformDependentData(int, void *);
	virtual void isNetworkEnabled(bool);
	virtual void isPowerVR();
	virtual void buyGame();
	virtual void finish();
	virtual void supportsTouchscreen();
	virtual void hasIDEProfiler();
	virtual void getPlatformStringVar(int);
	virtual void getApplicationId() = 0;
	virtual void getAvailableMemory();
	virtual void getBroadcastAddresses();
	virtual void getModelName();
	virtual void getDeviceId() = 0;
	virtual void createUUID() = 0;
	virtual void isFirstSnoopLaunch() = 0;
	virtual void hasHardwareInformationChanged() = 0;
	virtual void isTablet() = 0;
	virtual void registerUriListener(UriListener&);
	virtual void unregisterUriListener(UriListener&);
};
