#pragma once

enum EntityDamageCause
{
	CAUSE_CONTACT = 1,
	CAUSE_ENTITY_ATTACK,
	CAUSE_PROJECTILE,
	CAUSE_SUFFOCATION,
	CAUSE_FALL,
	CAUSE_FIRE,
	CAUSE_FIRE_TICK,
	CAUSE_LAVA,
	CAUSE_DROWNING,
	CAUSE_BLOCK_EXPLOSION,
	CAUSE_ENTITY_EXPLOSION,
	CAUSE_VOID,
	CAUSE_SUICIDE,
	CAUSE_MAGIC,
	CAUSE_WITHER,
	CAUSE_STARVE,
	CAUSE_ANVIL
};
